apiVersion: apps/v1
kind: Deployment
metadata:
  name: musician-app-deployment
  labels:
    app: musician-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musician-app
  template:
    metadata:
      labels:
        app: musician-app
    spec:
      containers:
        - name: musician-app
          image: olustrrax/musician-app:latest
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP