apiVersion: v1
kind: Service
metadata:
  name: musician-app-service
  labels:
    app: musician-app
spec:
  selector:
    app: musician-app
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http